[add] news animation with fadein fadeout
momokatw/tgee-frontend pull request #3
Opened 2020-12-09 14:38 UTC by season06

新增 id 在 navbar 的 button 和 內容的 div 中
以利用 js 來達成 FadeIn FadeOut 的動畫

2020-12-09 17:00 UTC, mitty-fun requested changes

2020-12-09 17:00 UTC, mitty-fun commented on staticfiles/index.js
> +      $active.not($item).css('display', 'none')
JQ fadeOut 動畫結束後應該自動會隱藏元素，這行還需要再加上 display-none 隱藏麻～？

2020-12-09 17:39 UTC, season06 commented on staticfiles/index.js
> +      $active.not($item).css('display', 'none')
如果快速點擊其他 button 會有內容堆疊的情況
加上 diplay-none 測試過後確認不會有這個問題~

2020-12-09 18:00 UTC, season06 commented on tgee/templates/index.html
> +            <button class="tgee-btn-secondary ml-1 ml-md-3" style="min-width: 100px;" id="#news1">官方訊息</button>
那如果我將 id 改成 href 呢?
會因為前面標籤不是 <a> 而有問題嗎?

2020-12-10 08:22 UTC, linroex commented
1. 幫不同分類的新聞做標示，方便測試時辨識
2. tab actived
3. 解 conflict

2020-12-10 08:25 UTC, linroex requested changes

2020-12-10 08:25 UTC, linroex commented on tgee/templates/index.html
> +            <button class="tgee-btn-secondary ml-1 ml-md-3" style="min-width: 100px;" id="#news1">官方訊息</button>
data-id 可能比較適合

參考： https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes

2020-12-10 08:25 UTC, linroex commented on tgee/templates/index.html
> +            <button class="tgee-btn-secondary ml-1 ml-md-3" style="min-width: 100px;" id="#news1">官方訊息</button>
另外要注意，HTML 標準來說，id 是有特別定義，在一個 HTML 內不能重複的

2020-12-10 08:25 UTC, linroex commented on tgee/templates/index.html
> +      <div id="nav" class="py-3 d-md-flex flex-column flex-md-row align-items-center">
nav 容易重複，也不夠明確（命名問題）

2020-12-10 09:07 UTC, season06 commented on tgee/templates/index.html
> +            <button class="tgee-btn-secondary ml-1 ml-md-3" style="min-width: 100px;" id="#news1">官方訊息</button>
OK, 改成 data-id 了

2020-12-10 09:08 UTC, season06 commented on tgee/templates/index.html
> +      <div id="nav" class="py-3 d-md-flex flex-column flex-md-row align-items-center">
已改成 news_nav

2020-12-12 12:46 UTC, mitty-fun approved these changes

2020-12-12 12:46 UTC, mitty-fun commented on staticfiles/index.js
> +    var $item = $($(this).attr('data-id'));
用 $.data 取元素綁定的資料會更好喔～
可以參考
[https://api.jquery.com/data/](https://api.jquery.com/data/)
[https://stackoverflow.com/questions/7261619/jquery-data-vs-attr](https://stackoverflow.com/questions/7261619/jquery-data-vs-attr)

2020-12-14 08:52 UTC, linroex commented on staticfiles/index.js
> +      $active.not($item).css('display', 'none')
@mitty-fun is this reolved?

2020-12-14 08:54 UTC, linroex commented on staticfiles/index.js
> +    var $item = $($(this).attr('data-id'));
@season06

2020-12-14 09:40 UTC, season06 commented on staticfiles/index.js
> +    var $item = $($(this).attr('data-id'));
改好了

2020-12-14 16:15 UTC, mitty-fun approved these changes

2020-12-14 16:15 UTC, mitty-fun commented on staticfiles/index.js
> +      $active.not($item).css('display', 'none')
@linroex  沒問題了

2020-12-15 16:12 UTC, merged